all: 
	
compile:
	g++ -fopenmp -std=c++11 -O3 val_test01_solved.cpp -o val_test01_solved
	g++ -fopenmp -std=c++11 -O3 val_test02_solved.cpp -o val_test02_solved
	g++ -fopenmp -O3 -std=c++11 -march=native MMult1.cpp -o MMult1
	g++ -fopenmp -O3 -std=c++11 -march=native MMult1_omp.cpp -o MMult1_omp
	g++ -fopenmp -std=c++11 -O3 omp_solved2.c -o omp_solved2
	g++ -fopenmp -std=c++11 -O3 omp_solved3.c -o omp_solved3
	g++ -fopenmp -std=c++11 -O3 omp_solved4.c -o omp_solved4
	g++ -fopenmp -std=c++11 -O3 omp_solved5.c -o omp_solved5
	g++ -fopenmp -std=c++11 -O3 omp_solved6.c -o omp_solved6
	g++ -fopenmp -O3 -std=c++11 -march=native gs2D-omp.cpp -o gs2D-omp
	g++ -fopenmp -O3 -std=c++11 -march=native jacobi2D-omp.c  -o jacobi2D-omp


